name: Build and Push Docker Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate image name
        id: img
        run: name="$(echo "ghcr.io/${{ github.repository }}" | tr "[:upper:]" "[:lower:]")"; echo "${name}"; echo "name=${name}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.img.outputs.name }}:${{ github.sha }}

      # Additionally create an image tagged as latest if we are on `main`
      # This should just re-use the existing image and not be a full build
      # but figuring out how to do that took too much time :P
      - name: Build and push Docker image
        id: docker_build_latest
        if: startsWith(github.ref, 'refs/heads/main')
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ steps.img.outputs.name }}:latest
